name: Fuzzing

on: [push, pull_request]

permissions:
  contents: read

jobs:
  fuzzing:
    name: Fuzz
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*

      - name: Install
        run: |
          npm install

      - name: Run fuzzing
        timeout-minutes: 10
        run: |
          npm run fuzz

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ failure() }}
        with:
          name: undici-fuzz-results-${{ github.sha }}
          path: |
            corpus/
            crash-*
            fuzz-results-*.json
