name: Publish undici-types

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: node scripts/generate-undici-types-package-json.js
      - run: npm publish
        working-directory: './types'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
